config/routes.rb
Rails.application.routes.draw do
  root to: 'home#top'
  devise_for :users

  resources :books, only: [:new, :create, :index, :show, :edit, :destroy, :update] do
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  resources :users, only: [:show, :edit, :index, :create, :update]
  get "/home/about" => "home#about", as: "about"
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  # has_one_attached :image
  belongs_to :user
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  
  validates :title, presence: true
  validates :body, presence: true, length:{ maximum: 200 }

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
  
  validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
  
  validates :user_id, uniqueness: { scope: :book_id }
end

app/models/post_image.rb
class PostImage < ApplicationRecord
  has_one_attached :image
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

   has_many :books, dependent: :destroy
   has_many :book_comments, dependent: :destroy
   has_many :favorites, dependent: :destroy
   validates :name, uniqueness: true, length: {minimum: 2, maximum: 20}
   validates :introduction, length: { maximum: 50 }

   has_one_attached :profile_image
   
   def get_profile_image(width, height)
     unless profile_image.attached?
       file_path = Rails.root.join('app/assets/images/default-image.jpg')
       profile_image.attach(io: File.open(file_path), filename:'default-image.jpg', content_type: 'image/jpeg')
     end
     profile_image.variant(resize_to_limit: [width, height]).processed
   end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

before_action :authenticate_user!,except: [:top, :about]
before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
  end

end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController

  def create
    book = Book.find(params[:book_id])
    comment = current_user.book_comments.new(book_comment_params)
    comment.book_id = book.id
    comment.save
    redirect_to book_path(book)
  end

  def destroy
    BookComment.find(params[:id]).destroy
    redirect_to book_path(params[:book_id])
  end

  private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :is_matching_login_user, only: [:edit, :update]
  def new
    @book = Book.new
    @books = Book.all
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book)
    else
      @books = Book.all
      render :index
    end
  end

  def index
    @book = Book.new
    @books = Book.all
  end

  def show
    @book = Book.find(params[:id])
    @book_comment = BookComment
  end
  
  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end
  
  def update
    @book = Book.find(params[:id])
    @book.update(book_params)
    if @book.save
      flash[:notice] = "You have updated book successfully."
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end
  
  def edit
    @book = Book.find(params[:id])
  end

  private

  def book_params
    params.require(:book).permit(:title, :body, :user_id)
  end
  
  def is_matching_login_user
    book = Book.find(params[:id])
    unless book.user_id == current_user.id
      redirect_to books_path
    end
  end
    
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: book.id)
    favorite.save
    redirect_back(fallback_location: root_path)
  end

  def destroy
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: book.id)
    favorite.destroy
    redirect_back(fallback_location: root_path)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :is_matching_login_user, only: [:edit, :update]
  
  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def index
    @users = User.all
    @book = Book.new
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    if @user.save
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
  
  def is_matching_login_user
    user = User.find(params[:id])
    unless user.id == current_user.id
      redirect_to user_path(current_user.id)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_bookuser.html.erb
<div class="col-md-3">
    <h2>User info</h2>
    <%= image_tag book.user.get_profile_image(100, 100) %>
    <table class="table">
        <tbody>
            <tr></tr>
            <tr>
                <th>name</th>
                <th><%= book.user.name %></th>
            </tr>
            <tr>
                <th>introduction</th>
                <th><%= book.user.introduction %></th>
            </tr>
        </tbody>
    </table>
</div>

app/views/books/edit.html.erb
<div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  <h1>Editing Book</h1>
  <% if @book.errors.any? %>
    <div class="container px-5 px-sm-0">
        <div id="error_explanation">
            <h3><%= @book.errors.count %> errors prohibired this obj from being saved:</h3>
            <ul>
                <% @book.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
            </ul>
        </div>
    </div>
  <% end %>
  <%= form_with model:@book, local: true do |f| %>
  <div class="form-group">
    <label for="book_title">Title</label>
    <%= f.text_field :title, class: "form-control", id:"book_title"  %>
  </div>

  <div class="form-group">
    <label for="book_opinion">Opinion</label>
    <%= f.text_area :body, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.submit 'Update Book', class: "btn btn-success" %>
  </div>
  <% end %>
  <span>
    <%= link_to "Show", book_path %>
    |
    <%= link_to "Back", books_path %>
  </span>


</div>

app/views/books/index.html.erb
<% if @book.errors.any? %>
    <div class="container px-5 px-sm-0">
        <div id="error_explanation">
            <h3><%= @book.errors.count %> errors prohibired this obj from being saved:</h3>
            <ul>
                <% @book.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
            </ul>
        </div>
    </div>
<% end %>

<div class="col-md-3">
    <h2>User info</h2>
    <%= image_tag current_user.get_profile_image(100, 100) %>
    <table class="table">
        <tbody>
            <tr></tr>
            <tr>
                <th>name</th>
                <th><%= current_user.name %></th>
            </tr>
            <tr>
                <th>introduction</th>
                <th><%= current_user.introduction %></th>
            </tr>
        </tbody>
    </table>
    <div class="row">
        <%= link_to edit_user_path(current_user.id), class:"btn btn-outline-secondary btn-block" do %>
            <i class="fas fa-user-cog" aria-hidden="true"></i>
        <% end %>
    </div>
    
    <h2 class="mt-3">New book</h2>
    <%= form_with model:Book.new, url: books_path, method: :post do |f| %>
     <div class="form-group">
        <label for="book_title">Title</label>
        <%= f.text_field :title, class: "form-control" %>
     </div>

     <div class="form-group">
        <label for="book_opinion">Opinion</label>
        <%= f.text_area :body, class: "form-control" %>
     </div>

     <div class="form-group">
        <%= f.submit 'Create Book', class: "btn btn-success" %>
     </div>
    <% end %>
    
</div>

<div class="col-md-8 offset-md-1">
    <h2>Books</h2>
    <table class="table">
      <thead>
        <tr>
          <th></th>
          <th>Title</th>
          <th>Opinion</th>
          <th></th>
          <th></th>
          <th colspan="3"></th>
        </tr>
      </thead>
        <tbody>
            <% @books.each do |book| %>
            <tr>
                <td>
                    <%= link_to user_path(book.user.id) do %>
                        <%= image_tag book.user.get_profile_image(80, 80) %><br>
                    <% end %>
                </td>
                <td>
                    <%= link_to book_path(book.id) do %>
                        <%= book.title %>
                    <% end %>
                </td>
                <td>
                    <%= book.body %>
                </td>
                <td>
                    <% if book.favorited_by?(current_user) %>
                        <%= link_to book_favorites_path(book), method: :delete do %>
                            <i class="fas fa-heart" style="color: red;"><%= book.favorites.count %></i>
                        <% end %>
                    <% else %>
                        <%= link_to book_favorites_path(book), method: :post do %>
                            <i class="fas fa-heart" style="color: blue;"><%= book.favorites.count %></i>
                        <% end %>
                    <% end %>
                </td>
                <td>
                    <p>コメント件数：<%= book.book_comments.count %></p>
                </td>
            </tr>
            <% end %>
            
        </tbody>
    </table>
        

</div>

app/views/books/new.html.erb
<h1>Books#new</h1>
<p>Find me in app/views/books/new.html.erb</p>

app/views/books/show.html.erb
<%= render 'users/users', user: @book.user, book: Book.new %>

<div class="col-md-8 offset-md-1">
    <h2>Book detail</h2>
    <table class="table">
        <tbody>
            <tr>
                <td>
                    <%= link_to user_path(@book.user.id) do %>
                        <%= image_tag @book.user.get_profile_image(80, 80) %><br >
                        <%= @book.user.name %>
                    <% end %>
                </td>
                <td>
                    <%= link_to book_path(@book.id) do %>
                        <%= @book.title %>
                    <% end %>
                </td>
                <td>
                    <%= @book.body %>
                </td>
                <td>
                    <% if @book.favorited_by?(current_user) %>
                        <%= link_to book_favorites_path(@book), method: :delete do %>
                            <i class="fas fa-heart" style="color: red;"><%= @book.favorites.count %></i>
                        <% end %>
                    <% else %>
                        <%= link_to book_favorites_path(@book), method: :post do %>
                            <i class="fas fa-heart" style="color: blue;"><%= @book.favorites.count %></i>
                        <% end %>
                    <% end %>
                </td>
                <td>
                    コメント件数：<%= @book.book_comments.count %>
                </td>
                <% if @book.user == current_user %>
                <td>
                    <%= link_to "Edit", edit_book_path(@book), class:"btn btn-sm btn-success" %>
                </td>
                <td>
                    <%= link_to "Destroy", book_path(@book), class: "btn btn-sm btn-danger", method: :delete, "data-confirm" => "本当に削除しますか？" %>
                </td>
                <% end %>
            </tr>

        </tbody>
    </table>
    
    <div>
        <% @book.book_comments.each do |book_comment| %>
            <p>
            <%= link_to user_path(book_comment.user.id) do %>
                <%= image_tag book_comment.user.get_profile_image(80, 80) %><br >
                <%= book_comment.user.name %>
            <% end %>
            <%= book_comment.comment %>
            <% if book_comment.user == current_user %>
                <%= link_to "Destroy", book_book_comment_path(book_comment.book, book_comment), class: "btn btn-sm btn-danger", method: :delete %>
            <% end %>
            </p>
        <% end %>   
    </div>
    
    <div>
        <%= form_with model: [@book, @book_comment] do |f| %>
            <%= f.text_area :comment, class: "form-control" %><br/>
            <%= f.submit "送信" %>
        <% end %>
    </div>


</div>

app/views/home/about.html.erb
<h1 class="px-3 mx-auto">Welcome to
  <i class="fas fa-book" aria-hidden="true"></i><strong>Bookers</strong>!
</h1>

app/views/home/top.html.erb
<div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
  <h1>  welcome to
  <i class="fas fa-book" aria-hidden="true"></i><strong>Bookers</strong>
    !!
  </h1>
  <p>
    In 
    <i class="fas fa-book" aria-hidden="true"></i><strong>Bookers</strong>, 
  </p>
  <p>you can share and exchange your opinions , impressions , and emotions</p>
  <p>about various books!</p>
  <div class="btn-wrapper col-10 mx-auto">
    <div class="row">
      <a class="btn btn-info btn-sm btn-block mb-3 sign_in" href="/users/sign_in">Log in</a>
    </div>
    <div class="row">
      <a class="btn btn-success btn-sm btn-block sign_up" href="/users/sign_up">Sign up</a>
    </div>
    
  </div>
</div>

app/views/homes/about.html.erb
<h1 class="px-3 mx-auto">Welcome to
  <i class="fas fa-book" aria-hidden="true"></i><strong>Bookers</strong>!
</h1>

app/views/homes/top.html.erb
<div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
  <h1>  welcome to
  <i class="fas fa-book" aria-hidden="true"></i><strong>Bookers</strong>
    !!
  </h1>
  <p>
    In 
    <i class="fas fa-book" aria-hidden="true"></i><strong>Bookers</strong>, 
  </p>
  <p>you can share and exchange your opinions , impressions , and emotions</p>
  <p>about various books!</p>
  <div class="btn-wrapper col-10 mx-auto">
    <div class="row">
      <a class="btn btn-info btn-sm btn-block mb-3 sign_in" href="/users/sign_in">Log in</a>
    </div>
    <div class="row">
      <a class="btn btn-success btn-sm btn-block sign_up" href="/users/sign_up">Sign up</a>
    </div>
    
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
     <!-- FontAwsomeの読み込み-->
    <script src="https://kit.fontawesome.com/48880b6fe9.js" crossorigin="anonymous"></script>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="/">
            <span>Bookers</span>
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="true" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
              <li>
              <!--ホームに飛びたい、if文後の方がよい？-->
                <%= link_to user_path(current_user.id), class: 'nav-link text-light' do %>
                  <i class="fas fa-home" aria-hidden="true"></i>
                  Home
                <% end %>
              </li>
              <li>
              <!--usersページに飛びたい-->
                <%= link_to user_registration_path, class: 'nav-link text-light' do %>
                  <i class="fas fa-users" aria-hidden="true"></i>
                  Users
                <% end %>
              </li>
              <li>
              <!--booksページに飛びたい-->
                <%= link_to books_path, class: 'nav-link text-light' do %>
                  <i class="fas fa-book-open" aria-hidden="true"></i>
                  Books
                <% end %>
              </li>
              <li>
                <%= link_to destroy_user_session_path, method: :delete, class: 'nav-link text-light' do %>
                  <i class="fas fa-sign-out-alt" aria-hidden="true"></i>
                  Log out
                <% end %>
              </li>
            <% else %>
              <li>
              <!--ホームに飛びたい、if文後の方がよい？-->
                <%= link_to root_path, class: 'nav-link text-light' do %>
                  <i class="fas fa-home"aria-hidden="true"></i>
                  Home
                <% end %>
              </li>
              <li>
              <!--Aboutページにとびたい-->
                <%= link_to about_path, class: 'nav-link text-light' do %>
                  <i class="fas fa-link" aria-hidden="true"></i>
                  About
                <% end %>
              </li>
              <li>
                <%= link_to new_user_registration_path, class: 'nav-link text-light' do %>
                  <i class="fas fa-user-plus" aria-hidden="true"></i>
                  Sign up
                <% end %>
              </li>
              <li>
                <%= link_to new_user_session_path, class: 'nav-link text-light' do %>
                  <i class="fas fa-sign-in-alt" aria-hidden="true"></i>
                  Log in
                <% end %>
              </li>
            <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>

    <main>
      <p id="notice"><%= notice%></p>
      <div class="container">
        <div class="row">
          <%= yield %>
        </div>
      </div>
    </main>

    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/users/_users.html.erb
<div class="col-md-3">
    <h2>User info</h2>
    <%= image_tag user.get_profile_image(100, 100) %>
    <table class="table">
        <tbody>
            <tr></tr>
            <tr>
                <th>name</th>
                <th><%= user.name %></th>
            </tr>
            <tr>
                <th>introduction</th>
                <th><%= user.introduction %></th>
            </tr>
        </tbody>
    </table>
    <div class="row">
        <%= link_to edit_user_path(user.id), class:"btn btn-outline-secondary btn-block" do %>
            <i class="fas fa-user-cog" aria-hidden="true"></i>
        <% end %>
    </div>
    
    <h2 class="mt-3">New book</h2>
    <%= form_with model: book, url: books_path, method: :post do |f| %>
     <div class="form-group">
        <label for="book_title">Title</label>
        <%= f.text_field :title, class: "form-control" %>
     </div>

     <div class="form-group">
        <label for="book_opinion">Opinion</label>
        <%= f.text_area :body, class: "form-control" %>
     </div>

     <div class="form-group">
        <%= f.submit 'Create Book', class: "btn btn-success" %>
     </div>
    <% end %>
</div>

app/views/users/edit.html.erb
<div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  <h2>User info</h2>
  <% if @user.errors.any? %>
    <div class="container px-5 px-sm-0">
        <div id="error_explanation">
            <h3><%= @user.errors.count %> errors prohibired this obj from being saved:</h3>
            <ul>
                <% @user.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
            </ul>
        </div>
    </div>
  <% end %>
  <%= form_with model:@user, local: true do |f| %>
  <div class="form-group">
    <label for="user_name">Name</label>
    <%= f.text_field :name, class:"form-control", id:"user_name" %>
  </div>
  <div class="form-group">
    <label for="user_image">Image</label>
    <%= f.file_field :profile_image, class: "form-control-file", accept: "image/*", id:"user_profile_image" %>
  </div>
  <div class="form-group">
    <label for="user_introduction">Introduction</label>
    <%= f.text_area :introduction, class: "form-control", id:"user_introduction" %>
  </div>
  <div class="form-group">
    <%= f.submit "Update User", class: "btn btn-secondary" %>
  </div>
  <% end %>
</div>

app/views/users/index.html.erb
<%= render 'users', user: current_user, book: @book %>

<div class="col-md-8 offset-md-1">
  <h2>Users</h2>
  <table class="table">
    <thead>
      <tr>
        <th>image</th>
        <th>name</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
      <tr>
        <td>
          <%= image_tag user.get_profile_image(80, 80) %>
        </td>
        <td>
          <%= user.name %>
        </td>
        <td>
          <%= link_to "Show", user_path(user.id) %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/users/show.html.erb
<%= render 'users', user: @user, book: @book %>

<div class="col-md-8 offset-md-1">
    <h2>Books</h2>
    <table class="table table-hover table-inverse">
        <thead>
            <tr>
                <th></th>
                <th>Title</th>
                <th>Opinion</th>
                <th></th>
                <th></th>
                <th colspan="3"></th>
            </tr>
        </thead>
        <tbody>
            <% @books.each do |book| %>
            <tr>
                <td>
                    <%= link_to user_path(book.user.id) do %>
                        <%= image_tag @user.get_profile_image(80, 80) %>
                    <% end %>
                </td>
                <td>
                    <%= link_to book_path(book.id) do %>
                        <%= book.title %>
                    <% end %>
                </td>
                <td>
                    <%= book.body %>
                </td>
                <td>
                    <% if book.favorited_by?(current_user) %>
                        <%= link_to book_favorites_path(book), method: :delete do %>
                            <i class="fas fa-heart" style="color: red;"><%= book.favorites.count %></i>
                        <% end %>
                    <% else %>
                        <%= link_to book_favorites_path(book), method: :post do %>
                            <i class="fas fa-heart" style="color: blue;"><%= book.favorites.count %></i>
                        <% end %>
                    <% end %>
                </td>
                <td>
                    <p>コメント件数：<%= book.book_comments.count %></p>
                </td>
            </tr>
            <% end %>
        </tbody>
    </table>
        

</div>